// Bộ cặp từ khóa tiếng Việt cho "AI Là Gián Điệp?"
// Mỗi cặp gồm 2 từ KHÁC nhau nhưng CÓ LIÊN QUAN: dân thường nhận `civilian`, gián điệp nhận `spy`.
// Mở rộng dễ dàng bằng cách thêm phần tử mới vào đúng danh mục.

export type KwDifficulty = "EASY" | "MEDIUM" | "HARD";

export interface KeywordPair {
  civilian: string;
  spy: string;
  category: string;
  difficulty: KwDifficulty;
}

type Cat = Omit<KeywordPair, "category">;

const make = (category: string, items: Cat[]): KeywordPair[] =>
  items.map((i) => ({ ...i, category }));

const E: KwDifficulty = "EASY";
const M: KwDifficulty = "MEDIUM";
const H: KwDifficulty = "HARD";

export const CATEGORIES: { id: string; label: string; emoji: string }[] = [
  { id: "do-an", label: "Đồ ăn", emoji: "🍜" },
  { id: "do-uong", label: "Đồ uống", emoji: "🧋" },
  { id: "dong-vat", label: "Động vật", emoji: "🐯" },
  { id: "truong-hoc", label: "Trường học", emoji: "🎒" },
  { id: "nghe-nghiep", label: "Nghề nghiệp", emoji: "👔" },
  { id: "cong-nghe", label: "Công nghệ", emoji: "💻" },
  { id: "mang-xa-hoi", label: "Mạng xã hội", emoji: "📱" },
  { id: "nguoi-noi-tieng", label: "Người nổi tiếng", emoji: "⭐" },
  { id: "dia-danh", label: "Địa danh", emoji: "🗺️" },
  { id: "tinh-thanh", label: "Tỉnh thành", emoji: "🏙️" },
  { id: "thuong-hieu", label: "Thương hiệu Việt", emoji: "🏷️" },
  { id: "phim-anh", label: "Phim ảnh", emoji: "🎬" },
  { id: "am-nhac", label: "Âm nhạc", emoji: "🎵" },
  { id: "the-thao", label: "Thể thao", emoji: "⚽" },
  { id: "do-vat", label: "Đồ vật", emoji: "🪑" },
  { id: "phuong-tien", label: "Phương tiện", emoji: "🛵" },
  { id: "du-lich", label: "Du lịch", emoji: "🏖️" },
  { id: "internet", label: "Internet & Meme", emoji: "😂" },
];

export const KEYWORD_PAIRS: KeywordPair[] = [
  ...make("do-an", [
    { civilian: "Phở", spy: "Bún bò", difficulty: E },
    { civilian: "Bánh mì", spy: "Bánh bao", difficulty: E },
    { civilian: "Cơm tấm", spy: "Cơm gà", difficulty: E },
    { civilian: "Bún chả", spy: "Bún đậu", difficulty: M },
    { civilian: "Bánh xèo", spy: "Bánh khọt", difficulty: M },
    { civilian: "Gỏi cuốn", spy: "Chả giò", difficulty: M },
    { civilian: "Hủ tiếu", spy: "Mì Quảng", difficulty: M },
    { civilian: "Bánh chưng", spy: "Bánh tét", difficulty: E },
    { civilian: "Xôi", spy: "Cháo", difficulty: E },
    { civilian: "Bánh cuốn", spy: "Bánh ướt", difficulty: H },
    { civilian: "Nem rán", spy: "Nem chua", difficulty: M },
    { civilian: "Lẩu", spy: "Nướng", difficulty: E },
    { civilian: "Bánh tráng trộn", spy: "Bánh tráng nướng", difficulty: M },
    { civilian: "Chè", spy: "Sữa chua", difficulty: E },
    { civilian: "Pizza", spy: "Hamburger", difficulty: E },
    { civilian: "Sushi", spy: "Sashimi", difficulty: H },
    { civilian: "Mì tôm", spy: "Miến", difficulty: E },
    { civilian: "Bún riêu", spy: "Bún ốc", difficulty: H },
    { civilian: "Bánh flan", spy: "Rau câu", difficulty: M },
    { civilian: "Cá kho", spy: "Thịt kho", difficulty: M },
  ]),
  ...make("do-uong", [
    { civilian: "Trà sữa", spy: "Cà phê sữa", difficulty: E },
    { civilian: "Cà phê đen", spy: "Cà phê sữa", difficulty: M },
    { civilian: "Nước mía", spy: "Nước dừa", difficulty: E },
    { civilian: "Trà chanh", spy: "Trà đào", difficulty: M },
    { civilian: "Sinh tố", spy: "Nước ép", difficulty: M },
    { civilian: "Coca", spy: "Pepsi", difficulty: E },
    { civilian: "Bia", spy: "Rượu", difficulty: E },
    { civilian: "Sữa đậu nành", spy: "Sữa tươi", difficulty: M },
    { civilian: "Cacao", spy: "Sô cô la nóng", difficulty: H },
    { civilian: "Trà đá", spy: "Nhân trần", difficulty: M },
    { civilian: "Bạc xỉu", spy: "Cà phê sữa", difficulty: H },
    { civilian: "Soda", spy: "Nước ngọt có ga", difficulty: M },
    { civilian: "Nước suối", spy: "Nước khoáng", difficulty: H },
    { civilian: "Matcha", spy: "Trà xanh", difficulty: H },
  ]),
  ...make("dong-vat", [
    { civilian: "Chó", spy: "Mèo", difficulty: E },
    { civilian: "Hổ", spy: "Sư tử", difficulty: E },
    { civilian: "Voi", spy: "Tê giác", difficulty: M },
    { civilian: "Cá heo", spy: "Cá voi", difficulty: M },
    { civilian: "Gà", spy: "Vịt", difficulty: E },
    { civilian: "Trâu", spy: "Bò", difficulty: E },
    { civilian: "Khỉ", spy: "Đười ươi", difficulty: M },
    { civilian: "Cá sấu", spy: "Thằn lằn", difficulty: M },
    { civilian: "Rắn", spy: "Lươn", difficulty: M },
    { civilian: "Ếch", spy: "Cóc", difficulty: M },
    { civilian: "Đại bàng", spy: "Diều hâu", difficulty: H },
    { civilian: "Chuột", spy: "Sóc", difficulty: M },
    { civilian: "Gấu trúc", spy: "Gấu Bắc Cực", difficulty: M },
    { civilian: "Ong", spy: "Kiến", difficulty: E },
    { civilian: "Bướm", spy: "Chuồn chuồn", difficulty: M },
    { civilian: "Rùa", spy: "Ba ba", difficulty: H },
    { civilian: "Ngựa", spy: "Lừa", difficulty: M },
    { civilian: "Cừu", spy: "Dê", difficulty: M },
  ]),
  ...make("truong-hoc", [
    { civilian: "Bút bi", spy: "Bút chì", difficulty: E },
    { civilian: "Bảng đen", spy: "Bảng trắng", difficulty: M },
    { civilian: "Giáo viên", spy: "Gia sư", difficulty: M },
    { civilian: "Bài kiểm tra", spy: "Bài thi", difficulty: M },
    { civilian: "Cặp sách", spy: "Ba lô", difficulty: E },
    { civilian: "Sách giáo khoa", spy: "Vở bài tập", difficulty: M },
    { civilian: "Lớp học", spy: "Giảng đường", difficulty: M },
    { civilian: "Phấn", spy: "Bút lông", difficulty: M },
    { civilian: "Giờ ra chơi", spy: "Giờ nghỉ trưa", difficulty: H },
    { civilian: "Lớp trưởng", spy: "Bí thư", difficulty: H },
    { civilian: "Toán", spy: "Lý", difficulty: E },
    { civilian: "Tốt nghiệp", spy: "Khai giảng", difficulty: M },
  ]),
  ...make("nghe-nghiep", [
    { civilian: "Bác sĩ", spy: "Y tá", difficulty: E },
    { civilian: "Công an", spy: "Bộ đội", difficulty: E },
    { civilian: "Đầu bếp", spy: "Phụ bếp", difficulty: M },
    { civilian: "Ca sĩ", spy: "Nhạc sĩ", difficulty: M },
    { civilian: "Lập trình viên", spy: "Tester", difficulty: H },
    { civilian: "Tài xế", spy: "Phụ xe", difficulty: M },
    { civilian: "Giáo viên", spy: "Hiệu trưởng", difficulty: M },
    { civilian: "Phi công", spy: "Tiếp viên", difficulty: M },
    { civilian: "Thợ cắt tóc", spy: "Thợ làm nail", difficulty: M },
    { civilian: "Nông dân", spy: "Ngư dân", difficulty: E },
    { civilian: "Luật sư", spy: "Thẩm phán", difficulty: H },
    { civilian: "Shipper", spy: "Tài xế taxi", difficulty: M },
    { civilian: "Streamer", spy: "YouTuber", difficulty: H },
    { civilian: "Diễn viên", spy: "Người mẫu", difficulty: M },
  ]),
  ...make("cong-nghe", [
    { civilian: "iPhone", spy: "Samsung", difficulty: E },
    { civilian: "Laptop", spy: "Máy tính bàn", difficulty: E },
    { civilian: "Chuột máy tính", spy: "Bàn phím", difficulty: E },
    { civilian: "Tai nghe", spy: "Loa", difficulty: E },
    { civilian: "Sạc dự phòng", spy: "Cục sạc", difficulty: M },
    { civilian: "Wifi", spy: "4G", difficulty: M },
    { civilian: "Máy ảnh", spy: "Máy quay", difficulty: M },
    { civilian: "Smartwatch", spy: "Vòng tay thông minh", difficulty: H },
    { civilian: "Robot", spy: "AI", difficulty: M },
    { civilian: "USB", spy: "Thẻ nhớ", difficulty: M },
    { civilian: "Máy in", spy: "Máy scan", difficulty: M },
    { civilian: "Màn hình", spy: "Tivi", difficulty: M },
    { civilian: "ChatGPT", spy: "Google", difficulty: H },
  ]),
  ...make("mang-xa-hoi", [
    { civilian: "Facebook", spy: "Instagram", difficulty: E },
    { civilian: "TikTok", spy: "YouTube", difficulty: E },
    { civilian: "Zalo", spy: "Messenger", difficulty: E },
    { civilian: "Story", spy: "Reels", difficulty: M },
    { civilian: "Like", spy: "Thả tim", difficulty: M },
    { civilian: "Comment", spy: "Inbox", difficulty: M },
    { civilian: "Livestream", spy: "Video", difficulty: M },
    { civilian: "Follow", spy: "Kết bạn", difficulty: M },
    { civilian: "Hashtag", spy: "Tag", difficulty: H },
    { civilian: "Group", spy: "Fanpage", difficulty: H },
    { civilian: "Twitter", spy: "Threads", difficulty: H },
    { civilian: "Telegram", spy: "Discord", difficulty: M },
  ]),
  ...make("nguoi-noi-tieng", [
    { civilian: "Sơn Tùng M-TP", spy: "Đen Vâu", difficulty: M },
    { civilian: "Hoài Linh", spy: "Trấn Thành", difficulty: M },
    { civilian: "Quang Hải", spy: "Công Phượng", difficulty: M },
    { civilian: "Mỹ Tâm", spy: "Hồ Ngọc Hà", difficulty: M },
    { civilian: "Trường Giang", spy: "Trấn Thành", difficulty: H },
    { civilian: "Độ Mixi", spy: "Cris Phan", difficulty: H },
    { civilian: "ViruSs", spy: "Pewpew", difficulty: H },
    { civilian: "Hari Won", spy: "Đông Nhi", difficulty: H },
    { civilian: "Hieuthuhai", spy: "Soobin", difficulty: H },
    { civilian: "Lê Văn Sỹ", spy: "Bùi Tiến Dũng", difficulty: H },
    { civilian: "Châu Bùi", spy: "Quỳnh Anh Shyn", difficulty: H },
  ]),
  ...make("dia-danh", [
    { civilian: "Hồ Gươm", spy: "Hồ Tây", difficulty: M },
    { civilian: "Vịnh Hạ Long", spy: "Tràng An", difficulty: M },
    { civilian: "Phố cổ Hội An", spy: "Kinh thành Huế", difficulty: M },
    { civilian: "Chợ Bến Thành", spy: "Chợ Đồng Xuân", difficulty: H },
    { civilian: "Bà Nà Hills", spy: "Sun World", difficulty: H },
    { civilian: "Lăng Bác", spy: "Văn Miếu", difficulty: M },
    { civilian: "Phong Nha", spy: "Sơn Đoòng", difficulty: H },
    { civilian: "Cầu Rồng", spy: "Cầu Vàng", difficulty: H },
    { civilian: "Dinh Độc Lập", spy: "Nhà thờ Đức Bà", difficulty: H },
    { civilian: "Núi Bà Đen", spy: "Fansipan", difficulty: M },
  ]),
  ...make("tinh-thanh", [
    { civilian: "Hà Nội", spy: "Hồ Chí Minh", difficulty: E },
    { civilian: "Đà Nẵng", spy: "Nha Trang", difficulty: E },
    { civilian: "Đà Lạt", spy: "Sa Pa", difficulty: M },
    { civilian: "Huế", spy: "Hội An", difficulty: M },
    { civilian: "Cần Thơ", spy: "Mỹ Tho", difficulty: M },
    { civilian: "Hải Phòng", spy: "Quảng Ninh", difficulty: M },
    { civilian: "Vũng Tàu", spy: "Phan Thiết", difficulty: M },
    { civilian: "Phú Quốc", spy: "Côn Đảo", difficulty: M },
    { civilian: "Buôn Ma Thuột", spy: "Pleiku", difficulty: H },
    { civilian: "Quy Nhơn", spy: "Tuy Hòa", difficulty: H },
  ]),
  ...make("thuong-hieu", [
    { civilian: "Vinamilk", spy: "TH True Milk", difficulty: M },
    { civilian: "Highlands", spy: "Phúc Long", difficulty: M },
    { civilian: "VinFast", spy: "Thaco", difficulty: M },
    { civilian: "Trung Nguyên", spy: "Cộng Cà Phê", difficulty: H },
    { civilian: "Bitis", spy: "Ananas", difficulty: H },
    { civilian: "Viettel", spy: "Vinaphone", difficulty: E },
    { civilian: "Thế Giới Di Động", spy: "FPT Shop", difficulty: M },
    { civilian: "Shopee", spy: "Lazada", difficulty: E },
    { civilian: "Grab", spy: "Be", difficulty: E },
    { civilian: "Vietjet", spy: "Bamboo Airways", difficulty: M },
    { civilian: "Hảo Hảo", spy: "Omachi", difficulty: M },
  ]),
  ...make("phim-anh", [
    { civilian: "Mắt Biếc", spy: "Tôi Thấy Hoa Vàng Trên Cỏ Xanh", difficulty: H },
    { civilian: "Bố Già", spy: "Nhà Bà Nữ", difficulty: M },
    { civilian: "Hai Phượng", spy: "Lật Mặt", difficulty: M },
    { civilian: "Doraemon", spy: "Conan", difficulty: E },
    { civilian: "Avengers", spy: "Justice League", difficulty: M },
    { civilian: "Squid Game", spy: "Alice in Borderland", difficulty: H },
    { civilian: "Spider-Man", spy: "Batman", difficulty: E },
    { civilian: "Người Nhện", spy: "Siêu Nhân", difficulty: E },
    { civilian: "Reply 1988", spy: "Hậu Duệ Mặt Trời", difficulty: H },
    { civilian: "Tom & Jerry", spy: "Mickey", difficulty: M },
  ]),
  ...make("am-nhac", [
    { civilian: "Bolero", spy: "Nhạc trữ tình", difficulty: H },
    { civilian: "Rap", spy: "Hip-hop", difficulty: M },
    { civilian: "Guitar", spy: "Ukulele", difficulty: M },
    { civilian: "Piano", spy: "Organ", difficulty: M },
    { civilian: "Karaoke", spy: "Hát live", difficulty: M },
    { civilian: "Trống", spy: "Đàn bầu", difficulty: M },
    { civilian: "Sáo", spy: "Kèn", difficulty: M },
    { civilian: "Nhạc Vàng", spy: "Nhạc Đỏ", difficulty: H },
    { civilian: "EDM", spy: "Nhạc Sàn", difficulty: H },
    { civilian: "Rap Việt", spy: "King Of Rap", difficulty: H },
  ]),
  ...make("the-thao", [
    { civilian: "Bóng đá", spy: "Bóng rổ", difficulty: E },
    { civilian: "Cầu lông", spy: "Tennis", difficulty: E },
    { civilian: "Bơi lội", spy: "Lặn", difficulty: M },
    { civilian: "Chạy bộ", spy: "Đi bộ", difficulty: M },
    { civilian: "Bóng bàn", spy: "Tennis", difficulty: M },
    { civilian: "Đá cầu", spy: "Nhảy dây", difficulty: M },
    { civilian: "Cờ vua", spy: "Cờ tướng", difficulty: M },
    { civilian: "Gym", spy: "Yoga", difficulty: M },
    { civilian: "Bida", spy: "Bowling", difficulty: M },
    { civilian: "Đua xe", spy: "Đua ngựa", difficulty: H },
    { civilian: "Boxing", spy: "Muay Thái", difficulty: H },
  ]),
  ...make("do-vat", [
    { civilian: "Ô (dù)", spy: "Áo mưa", difficulty: E },
    { civilian: "Đồng hồ", spy: "Lịch", difficulty: M },
    { civilian: "Quạt", spy: "Điều hòa", difficulty: E },
    { civilian: "Gương", spy: "Cửa kính", difficulty: M },
    { civilian: "Ổ khóa", spy: "Chìa khóa", difficulty: M },
    { civilian: "Bàn chải", spy: "Lược", difficulty: M },
    { civilian: "Ghế", spy: "Sofa", difficulty: E },
    { civilian: "Nồi cơm điện", spy: "Lò vi sóng", difficulty: M },
    { civilian: "Đèn pin", spy: "Nến", difficulty: M },
    { civilian: "Kéo", spy: "Dao", difficulty: E },
    { civilian: "Bút", spy: "Tẩy", difficulty: E },
    { civilian: "Ví", spy: "Túi xách", difficulty: M },
  ]),
  ...make("phuong-tien", [
    { civilian: "Xe máy", spy: "Xe đạp", difficulty: E },
    { civilian: "Ô tô", spy: "Xe tải", difficulty: E },
    { civilian: "Máy bay", spy: "Trực thăng", difficulty: M },
    { civilian: "Tàu hỏa", spy: "Tàu điện", difficulty: M },
    { civilian: "Thuyền", spy: "Phà", difficulty: M },
    { civilian: "Xe buýt", spy: "Xe khách", difficulty: M },
    { civilian: "Taxi", spy: "Xe ôm", difficulty: E },
    { civilian: "Xe ben", spy: "Máy xúc", difficulty: H },
    { civilian: "Xích lô", spy: "Xe lam", difficulty: H },
    { civilian: "Cano", spy: "Du thuyền", difficulty: H },
  ]),
  ...make("du-lich", [
    { civilian: "Biển", spy: "Hồ", difficulty: E },
    { civilian: "Khách sạn", spy: "Homestay", difficulty: M },
    { civilian: "Cắm trại", spy: "Trekking", difficulty: M },
    { civilian: "Vali", spy: "Ba lô", difficulty: M },
    { civilian: "Hộ chiếu", spy: "Vé máy bay", difficulty: M },
    { civilian: "Resort", spy: "Villa", difficulty: H },
    { civilian: "Tour", spy: "Phượt", difficulty: M },
    { civilian: "Sống ảo", spy: "Check-in", difficulty: H },
    { civilian: "Núi", spy: "Đồi", difficulty: M },
    { civilian: "Thác", spy: "Suối", difficulty: M },
  ]),
  ...make("internet", [
    { civilian: "Trend", spy: "Hot trend", difficulty: H },
    { civilian: "Flex", spy: "Khoe", difficulty: M },
    { civilian: "Crush", spy: "Gấu", difficulty: M },
    { civilian: "Phốt", spy: "Drama", difficulty: M },
    { civilian: "Hóng", spy: "Drama", difficulty: H },
    { civilian: "Cà khịa", spy: "Đá xoáy", difficulty: H },
    { civilian: "Trầm cảm", spy: "Tụt mood", difficulty: H },
    { civilian: "Gato", spy: "Ghen tị", difficulty: M },
    { civilian: "U là trời", spy: "Trời ơi tin được không", difficulty: H },
    { civilian: "Real", spy: "Fake", difficulty: M },
    { civilian: "Simp", spy: "Cuồng", difficulty: H },
    { civilian: "Mèo mặt khó ở", spy: "Ếch xanh buồn", difficulty: H },
  ]),
];

export const KEYWORD_COUNT = KEYWORD_PAIRS.length;
